const english = {
    // topmenu
    "toolCommonButton": "Test tool",

    "toolDeveloperButton": "Developer tool",
    "feedbackButton": "Feedback",
    "mailboxButton": "Mail",
    "wikiButton": "Wiki",
    // toolCommonButton
    // hero
    "Hero": "Hero",
    "ResetHero": "Reset hero",
    "RespawnHero": "Respawn hero",
    "RespawnHeroError1": "Unable to resurrect undead heroes",
    "RespawnHeroError2": "Only hero units can be resurrected",
    "ReplaceHero": "Replca hero",
    "SetGold": "Set gold",
    "SetGoldDescribe": "Setting the current money will set the input amount to unreliable money and clear reliable money.",
    "AddHero_Friend": "+ Friendly hero",
    "AddHero_Enemy": "+ Enemy hero",
    "ClearInventory": "Clear inventory",
    "LevelUp": "Level up",
    "MaxLevelUp": "Level max",
    "MaxLevelDescribe": "All spells will be learnt to max level.",
    "GetAbilityPoint": "+ Spell point",
    "RemoveAbilityPoint": "- Spell point",
    "RemoveAbilityPointError": "Insufficient spell point",
    "ReplaceAbility": "Replace ability",
    "ReplaceAbilityDescribe": "After changing skills, the built-in placeholder skill generic will be deleted_ Hidden, skills can be dragged and sorted, and the first 6 skills will be adapted to the default shortcut keys. The shining passive skills of Dawn Star will cause flickering and do not support replacement.",
    // unit
    "Unit": "unit",
    "EntInfoButton": "Entity info",
    "EntKVButton": "Entity kv",
    "EntKVButtonDescribe": "Will read kv every time the target is switched",
    "RefreshStatus": "Refresh Status",
    "AddDummy": "+ Dummy target",
    "AddUnit_Friend": "+ Friendly unit",
    "AddUnit_Enemy": "+ Enemy unit",
    "SelectUnit": "Select unit",
    "SelfMutilation": "Set HP to 1",
    "MoveToPoint": "Move to place",
    "MoveToCoordinate": "Move to coordinate",
    "MoveToCoordinateDescribe": "Enter the xyz coordinates, separated by a semicolon, and the height can be omitted. When the target coordinate is unreachable, it will move to a nearby location.",
    "RemoveUnit": "Remove entity",
    "RemoveUnitError": "You can't delete your own hero!",
    "AddInvulnerability": "Turn on invulnerability",
    "RemoveInvulnerability": "Turn off invulnerability",
    "SetAngle": "Set Angle",
    "SetAngleDescribe": "Enter a number from 0 to 360",
    // rune
    "Rune": "Rune",
    // map
    "Map": "Map",
    "SetCameraDistance": "Set camera distance",
    "SetCameraDistanceDescribe": "Adjusting too high will cause jamming, and we should act within our capabilities. It is recommended not to exceed 2000.",
    "HostTimescale": "Set game speed multiplier",
    "HostTimescaleDescribe": "Suggested range is 0-8, supporting decimals.",
    "DayNightCycle": "Switching day and night",
    "PauseDayNightCycle": "Pause day/night cycle",
    "EasyBuy": "EasyBuy",
    "FreeSpells": "Free spells",
    "HeroFastRespawn": "Fast respawn",
    "HeroSituRespawn": "Resurrection in Place",
    "PassiveGold": "No passive gold",
    "NoFogOfWar": "No Fog of War",
    "NoFogOfWarDescribe": "Change Fow of War will cause blue vision layer, you can place a ward to remove it.",


    // other
    "Other": "Other",
    "DotaLaunchCustomGame": "Reload game",
    "ScriptReload": "Reload lua",
    "Clear": "Clear console",
    "ClParticleLogCreates": "Print special effect names on the console",
    // endinfo
    "Entinfo": "Entity info",
    "entId": "Entity ID",
    "GetUnitName": "Entity Name",
    "GetClassname": "Entity Class Name",
    "GetAbsOrigin": "Origin",
    "GetDayTimeVisionRange": "Day vision",
    "GetNightTimeVisionRange": "Night vision",
    "GetAngles": "Get angles",
    "CanBeSeenByAnyOpposingTeam": "Is it in the other party's view",
    "GetBaseAttackTime": "Base Attack Time",
    "GetAttackSpeed": "Attack speed",
    "GetAttacksPerSecond": "Attacks per second",
    "GetSecondsPerAttack": "Time of each attack",
    "GetAttackAnimationPoint": "Base Attack Point",
    "GetCastPoint": "Current Attack Point",
    "GetProjectileSpeed": "Projectile speed",
    "HasFlyingVision": "Is Has Flying Vision",
    "GetHullRadius": "Bounding size",
    "GetPaddedCollisionRadius": "Collision size",
    "GetIdealSpeed": "Movement speed",
    "GetCooldownReduction": "Cooldown multiplier",
    "GetBaseDamage": " Base damage",
    "GetAverageTrueAttackDamage": "Average true attack damage",
    "GetAttackRangeBuffer": "Attack range buffer",
    "Script_GetAttackRange": "Attack range",
    "GetPhysicalArmorValue": "Physical armor",
    "GetMagicalArmorValue": "Magical armor",
    "GetStatusResistance": "Status resistance",
    "GetEvasion": "Evasion",
    "GetSpellAmplification": "Spell amplification",
    "GetCastRangeBonus": "Cast range bonus",
    "Health": "Health",
    "Mana": "Mana",
    "GetDeathXP": "Death XP",
    "GetGoldBounty": "Gold Bounty",
    "Edit": "Edit",
    // ent kv
    "EntKV": "Entity KV",
    // edit kv
    "AbilityCastPoint": "Cast point:",
    "AbilityChannelTime": "Channel time:",
    "AbilityManaCost": "Mana cst:",
    "AbilityCastRange": "Cast range:",
    "AbilityCooldown": "Cooldown:",
    "AbilityDamage": "Damage:",
    "AbilityDuration": "Duration:",
    "AbilityCharges": "Charges:",
    "AbilityChargeRestoreTime": "Charge restore time:",

    // developer
    "Ent": "Entity",
    "EntOverview": "Entity overview",
    "EntIsNull": "Entity IsNull",
    "EntNotIsAlive": "Entity Not IsAlive",
    "Particle": "Particle",
    "EntError": "You need to first click on Entity Overview to count entities",
    "ConfigAndStatus" : "Config and status",
    // recreation
    "feedbackTitle": "If you have any comments or suggestions about this map, you can send them to us so that we can continuously improve the gaming experience.",


    // other
    "True": "Yes",
    "False": "No",
    "Add": "Add",
    "Remove": "Remove",
    "Submit": "Submit",
    "Cancel": "Cancel",
    "Reset": "Reset",
    "Delete": "Delete",
    "IncorrectFormat": "The input format is incorrect",
    "NotIsCheatMode": "Cheating mode not enabled, this function cannot be used",
    "NoFunction": "The function does not exist",
    "AbilityDisabled": "ability has been disabled",
    "HasAbility": "You already have this ability",
    "NotIsCloudMode": "Cloud platform functionality not enabled",
    "NoMail": "no emails",
    "GetMailError" : "Failed to obtain email",
    "IsRead" : "Is read",
    "NotIsRead" : "Not is read",

}

GameUI.FiveCloudLocalize.Init("english", english)