const schinese = {
    // topmenu
    "toolCommonButton": "通用工具",

    "toolDeveloperButton": "开发者工具",
    "feedbackButton": "反馈",
    "mailboxButton": "邮箱",
    "wikiButton": "常用测试指令",
    // toolCommonButton
    // hero
    "Hero": "英雄",
    "ResetHero": "重置英雄",
    "RespawnHero": "复活英雄",
    "RespawnHeroError1": "不能复活未死亡的英雄",
    "RespawnHeroError2": "只能复活英雄单位",
    "ReplaceHero": "更换英雄",
    "SetGold": "设置金钱",
    "SetGoldDescribe": "设置当前金钱，会将输入的金额设置为不可靠金钱，同时清空可靠金钱。",
    "AddHero_Friend": "+ 友方英雄",
    "AddHero_Enemy": "+ 敌方英雄",
    "ClearInventory": "清空物品",
    "LevelUp": "升级",
    "MaxLevelUp": "升到满级",
    "MaxLevelDescribe": "同时会将所有技能学满",
    "GetAbilityPoint": "+ 技能点",
    "RemoveAbilityPoint": "- 技能点",
    "RemoveAbilityPointError": "技能点不足",
    "ReplaceAbility": "更换技能",
    "ReplaceAbilityDescribe": "更换技能后，会删除自带的占位技能generic_hidden，技能可拖动排序，前6个技能会适配默认的快捷键，破晓晨星的被动技能熠熠生辉会导致闪退，不支持更换。",
    // unit
    "Unit": "单位",
    "EntInfoButton": "实体信息",
    "EntKVButton": "实体KV",
    "EntKVButtonDescribe": "会在每次切换目标时读取kv",
    "RefreshStatus": "刷新状态",
    "AddDummy": "+ 傀儡目标",
    "AddUnit_Friend": "+ 友方单位",
    "AddUnit_Enemy": "+ 敌方单位",
    "SelectUnit": "选择要创建的单位",
    "SelfMutilation": "自残",
    "MoveToPoint": "移动至地点",
    "MoveToCoordinate": "移动至坐标",
    "MoveToCoordinateDescribe": "输入xyz坐标，以半角逗号分隔，高度可省略，目标坐标不可到达时，会移动到附近。",
    "RemoveUnit": "删除单位",
    "RemoveUnitError": "不能把自己的英雄给删了！",
    "AddInvulnerability": "添加无敌状态",
    "RemoveInvulnerability": "关闭无敌状态",
    "SetAngle": "设置朝向角度",
    "SetAngleDescribe": "输入0-360的一个数字",
    // rune
    "Rune": "神符",
    // map
    "Map": "地图",
    "SetCameraDistance": "调整视角高度",
    "SetCameraDistanceDescribe": "调太高会卡，量力而行，建议不要超过2000。",
    "HostTimescale": "设置游戏速度",
    "HostTimescaleDescribe": "建议范围0~8，支持小数。",
    "DayNightCycle": "切换昼夜",
    "PauseDayNightCycle": "停止昼夜轮替",
    "EasyBuy": "简易购买模式",
    "FreeSpells": "无限技能",
    "HeroFastRespawn": "快速复活",
    "HeroSituRespawn": "原地复活",
    "PassiveGold": "禁用每秒获得金钱",
    "NoFogOfWar": "禁用战争迷雾",
    "NoFogOfWarDescribe": "切换迷雾状态会出现蓝色视野区域，可以点击侦查守卫来消除",


    // other
    "Other": "其他",
    "DotaLaunchCustomGame": "重载游戏",
    "ScriptReload": "重载lua",
    "Clear": "清空控制台",
    "ClParticleLogCreates": "在控制台打印特效名",
    // endinfo
    "Entinfo": "实体信息",
    "entId": "实体 ID",
    "GetUnitName": "实体名称",
    "GetClassname": "类别名称",
    "GetAbsOrigin": "坐标",
    "GetDayTimeVisionRange": "白天视野",
    "GetNightTimeVisionRange": "夜间视野",
    "GetAngles": "朝向角度",
    "CanBeSeenByAnyOpposingTeam": "是否在对方视野",
    "GetBaseAttackTime": "基础攻击间隔",
    "GetAttackSpeed": "攻击速度",
    "GetAttacksPerSecond": "每秒攻击次数",
    "GetSecondsPerAttack": "每次攻击时间",
    "GetAttackAnimationPoint": "基础攻击前摇",
    "GetCastPoint": "当前攻击前摇",
    "GetProjectileSpeed": "弹道速度",
    "HasFlyingVision": "是否有空中视野",
    "GetHullRadius": "边界体积",
    "GetPaddedCollisionRadius": "碰撞体积",
    "GetIdealSpeed": "移动速度",
    "GetCooldownReduction": "冷却时间倍率",
    "GetBaseDamage": "基础攻击力",
    "GetAverageTrueAttackDamage": "总攻击力",
    "GetAttackRangeBuffer": "攻击缓冲距离",
    "Script_GetAttackRange": "攻击距离",
    "GetPhysicalArmorValue": "护甲",
    "GetMagicalArmorValue": "魔抗",
    "GetStatusResistance": "状态抗性",
    "GetEvasion": "闪避",
    "GetSpellAmplification": "技能增强",
    "GetCastRangeBonus": "施法距离加成",
    "Health": "血量",
    "Mana": "蓝量",
    "GetDeathXP": "死亡经验给与",
    "GetGoldBounty": "死亡金钱给与",
    "Edit": "修改",
    // ent kv
    "EntKV": "实体KV",
    // edit kv
    "AbilityCastPoint": "施法前摇：",
    "AbilityChannelTime": "吟唱时间：",
    "AbilityManaCost": "魔法消耗：",
    "AbilityCastRange": "施法距离：",
    "AbilityCooldown": "冷却时间：",
    "AbilityDamage": "技能伤害：",
    "AbilityDuration": "持续时间：",
    "AbilityCharges": "充能点数：",
    "AbilityChargeRestoreTime": "充能时间：",

    // developer
    "Ent": "实体",
    "EntOverview": "实体概览",
    "EntIsNull": "空实体",
    "EntNotIsAlive": "死亡实体",
    "Particle": "特效",
    "EntError" : "需要先点击实体概览统计实体",
    "ConfigAndStatus" : "当前配置状态",
    // recreation
    "feedbackTitle": "您如果对本地图有任何的意见和建议，都可以发送给我们，以便我们不断改进游戏体验。",


    // other
    "True": "是",
    "False": "否",
    "Add": "添加",
    "Remove": "删除",
    "Submit": "确定",
    "Cancel": "取消",
    "Reset": "重置",
    "Delete": "删除",
    "IncorrectFormat": "输入的格式不正确",
    "NotIsCheatMode": "未开启作弊模式，该功能无法使用",
    "NoFunction": "该函数不存在",
    "AbilityDisabled": "该技能已禁用",
    "HasAbility": "已拥有该技能",
    "NotIsCloudMode" : "未开启网络功能",
    "NoMail" : "暂无邮件",
    "GetMailError" : "获取邮件失败",
    "IsRead" : "已读",
    "NotIsRead" : "未读",
    

}

GameUI.FiveCloudLocalize.Init("schinese", schinese)